meta:
  work_folder: ./training_logs_cl_pilot
  random_seed: 42
  fp64: false
  print_grad: false
  save_debug_data: false
dataset:
- config: ./processed_data/dataset_config.yaml
  batch_size: 16
  shuffle: true
  cluster: true
  train_ratio: 0.9
  loss_weight: 1.0
  loss:
  - loss_type: InterEnergyPolMSE
    weight: 1.0
    kwargs:
      force_cutoff:
      - 50.0
      - 80.0
      clamp: 10.0
      decay: 2.0
  - loss_type: InterEnergyDispMSE
    weight: 1.0
    kwargs:
      force_cutoff:
      - 50.0
      - 80.0
      clamp: 10.0
      decay: 2.0
  - loss_type: InterEnergyElecPauliMSE
    weight: 1.0
    kwargs:
      force_cutoff:
      - 50.0
      - 80.0
      clamp: 10.0
      decay: 2.0
  - loss_type: InterEnergyCTMSE
    weight: 1.0
    kwargs:
      force_cutoff:
      - 50.0
      - 80.0
      clamp: 10.0
      decay: 2.0
  - loss_type: InterEnergyMSE
    weight: 10.0
    kwargs:
      force_cutoff:
      - 50.0
      - 80.0
      clamp: 10.0
      decay: 2.0
  aux_loss:
  - loss_type: InterEnergyPolMSE
    kwargs:
      force_cutoff:
      - 50.0
      - 80.0
      clamp: 10.0
      decay: 2.0
  - loss_type: InterEnergyDispMSE
    kwargs:
      force_cutoff:
      - 50.0
      - 80.0
      clamp: 10.0
      decay: 2.0
  - loss_type: InterEnergyElecPauliMSE
    kwargs:
      force_cutoff:
      - 50.0
      - 80.0
      clamp: 10.0
      decay: 2.0
  - loss_type: InterEnergyCTMSE
    kwargs:
      force_cutoff:
      - 50.0
      - 80.0
      clamp: 10.0
      decay: 2.0
  - loss_type: InterEnergyMSE
    kwargs:
      force_cutoff:
      - 50.0
      - 80.0
      clamp: 10.0
      decay: 2.0
  - loss_type: InterEnergyPolMSE
  - loss_type: InterEnergyDispMSE
  - loss_type: InterEnergyElecPauliMSE
  - loss_type: InterEnergyCTMSE
  - loss_type: InterEnergyMSE
- aux_loss:
  - kwargs:
      clamp: 10.0
      decay: 2.0
      force_cutoff:
      - 50.0
      - 80.0
    loss_type: InterEnergyPolMSE
  - kwargs:
      clamp: 10.0
      decay: 2.0
      force_cutoff:
      - 50.0
      - 80.0
    loss_type: InterEnergyDispMSE
  - kwargs:
      clamp: 10.0
      decay: 2.0
      force_cutoff:
      - 50.0
      - 80.0
    loss_type: InterEnergyElecPauliMSE
  - kwargs:
      clamp: 10.0
      decay: 2.0
      force_cutoff:
      - 50.0
      - 80.0
    loss_type: InterEnergyCTMSE
  - kwargs:
      clamp: 10.0
      decay: 2.0
      force_cutoff:
      - 50.0
      - 80.0
    loss_type: InterEnergyMSE
  - loss_type: InterEnergyPolMSE
  - loss_type: InterEnergyDispMSE
  - loss_type: InterEnergyElecPauliMSE
  - loss_type: InterEnergyCTMSE
  - loss_type: InterEnergyMSE
  batch_size: 2
  cluster: true
  config: ../0_data_preparation/cl_pilot/processed_data/dataset_config.yaml
  loss:
  - kwargs:
      clamp: 10.0
      decay: 2.0
      force_cutoff:
      - 50.0
      - 80.0
    loss_type: InterEnergyPolMSE
    weight: 1.0
  - kwargs:
      clamp: 10.0
      decay: 2.0
      force_cutoff:
      - 50.0
      - 80.0
    loss_type: InterEnergyDispMSE
    weight: 1.0
  - kwargs:
      clamp: 10.0
      decay: 2.0
      force_cutoff:
      - 50.0
      - 80.0
    loss_type: InterEnergyElecPauliMSE
    weight: 1.0
  - kwargs:
      clamp: 10.0
      decay: 2.0
      force_cutoff:
      - 50.0
      - 80.0
    loss_type: InterEnergyCTMSE
    weight: 1.0
  - kwargs:
      clamp: 10.0
      decay: 2.0
      force_cutoff:
      - 50.0
      - 80.0
    loss_type: InterEnergyMSE
    weight: 10.0
  loss_weight: 1.0
  shuffle: true
  train_ratio: 0.67
  train_all: true
model:
  check_point: ../../byteff2/trained_models/optimal.pt
  graph_block:
    feature_layer:
      atom_embedding_dim: 32
      node_mlp_dims:
      - 64
      - 256
      - 2
      edge_mlp_dims:
      - 64
      - 256
      - 2
      act: gelu
    gnn_layer:
      gnn_type: EGT
      gnn_dims:
      - 256
      - 256
      - 4
      jk: cat
      act: gelu
      heads: 16
      at_channels: 16
      ffn_dims:
      - 256
      - 2
  ff_block:
  - type: MMBondedConj
    pre_mlp_dims:
    - 256
    - 256
    - 3
    post_mlp_dims:
    - 256
    - 256
    - 1
    out_mlp_dims:
    - 256
    - 4
    tanh_output: 20.0
    act: gelu
  - type: ChargeVolume
    pre_mlp_dims:
    - 256
    - 256
    - 3
    out_mlp_dims:
    - 256
    - 3
    act: gelu
  - type: Exp6Pol
    pre_mlp_dims:
    - 256
    - 256
    - 3
    out_mlp_dims:
    - 256
    - 3
    act: gelu
    ind14: 0.5
    charge14: 0.5
    vdw14: 0.5
    pol_damping_factor: 0.39
    s12: 1.5
    disp_damping_factor: 120.0
    li_damp_clip: 0.2
    fix_li_alpha: 1.0e-06
training:
  valid_interval: 4
  ckpt_interval: 12
  max_epoch: 40
  grad_clip: 1.0
  optimizer:
    type: RAdam
    lr:
      Graph: 0.0
      MMBondedConj: 0.0
      ChargeVolume: 2.0e-05
      Exp6Pol: 0.0002
  scheduler:
    type: ReduceLROnPlateau
    factor: 0.5
    patience: 8
    threshold_mode: abs
    threshold: 1.0e-09
  early_stop_patience: 20
  ignore_tolerance: 1.0e-06
